---
title: "Template for chapters"
output: html_document
date: '2022-05-13'
editor_options: 
  markdown: 
    wrap: 72
---

here wrongling with structure indeas : sort of sand box  
trying to keep coherent templates 

## Key words

-   (edit) before a part to heavily edit
-   (error)
-   add
-   (comm) : comme info to tackle as such, ex common to GUI and R, but
    now only in GUI

## Flow of (old) info

split between \* algos : \* tools +GUI +Packages \* methods (general
bricks)

## Chapter on Algorithms

list..
* SA
* SA on HF

What do we want here : 


Theory : 
Tool specific

This will be the template for each algo

### Purpose

### Parameters

#### Common infos (in the algo part)
#### specific infos declined by tools GUI and R (links)
link to tool part

### output
#### diagnostics common info (in the algo part)
#### diagnostics infos declined by tools GUI and R
#### series common
#### series specific : link to tool part

## Tools

### Available Algos list
* quick links


### Global info for each Tool ex GUI and R Packages
* overwiew independent of algo details 
* installation (might be slightly different dor R packages by algo)
* global display and philo 
+ ex list of lists : the output..with repetition of the input 

3.  For each algo 

* SA : steps with GUI (2 sub algo pre adj and decomp)
Table : list of steps with links 

steps 






### Methods

key : focus on building blocs
