---
title: "Comments on building process"
output: html_document
date: '2022-05-15'
---

make a qmd file

capture config of infos is key : zero paper at the end of the session (unless exceptional draw)

## Steps

NOW as pasting of old content is over : hurra !!

### make a list of CHUNKS

### split old info between algos, tools methods

### table with : chunk, tasks, timeline and outsourcing

## GUI : simplify (cf greg), but maybe not destroy ?

global view (print ?) and RECYCLE

### global menus

### importing data

### contextual menus (ex on a series)

### chart tools

### build around SAP, ws...(documents and co just mention and set link if identical)

#### input : where to set, read and retrieve (output) the parameters

#### output : diagnostics + series

general ides ex : common RJD and GUI then *GUI* rjd

## Added Value

If I had to sell and pitch the product

-   Hub for good links, but put into context

-   shorter texte plus aéré : how to make this happen

-   how do user cases appear = worked examples

-   embeded R code and "exercises"

-   example : plug-ins bbk, rjd

## Spill overs

### R packages help packges

### Vignettes

## Heuristics

type of work, mental stat, slot (W or H or OTG)\\

#### Type 1: Technical improvements

Doesn't require a deep technical dive in\
Editing

#### Writing of "new" content

including heavy restructuring, and mostly uncovered parts

Workflow principles

OKRs

Aux Info to consult overleaf JD+ q&A (à re config) JD+ explo interface

Global improvements (outsourcing possibe) - gather all references - clean up Tables - formulas

Ubiquitous modifs itemize references ? on refera un biblio .bib cross ref appear : modif mater more lear tables

Chapter Templates Tools itemize obj :

Current steps Info itemize read Bookdown guide (mostly home, not only, pull out) check carto with JP UtilitR code

Moi : core work itemize recycle add spectral analysis chapter in "Methods part" create X separate GUI, from theory from R

why is methods part here: to allow a two-step approach

Outsourcing Tanguy(first) + Tsace or Tsaug members (post next reu stace) GUI part :

replace descriptiowth : 1 tableau 1 picture (highlighted commented) + video tutos (attetion surcharge, juste souris, pas zoom, sort og GIF ?) harmonize police tables tutos videos for GUI ?

GUI heck vs version 3 and update pictures replace with GIFS

Cat 1: brand new pages HF pages

Cat 2:

Cat 3: fully recycle first, clean up second
