# Seasonal adjustment of high-frequency data {.unnumbered}

## Motivation: data specificities

Infra monthly data displays multiple and non integer periodicities which cannot be dealt with classical versions of SA algorithms. JD+ provides tailored versions of these algorithms.

Link to worked example (Daily French births)

## Available algorithms

code here and/or link to R packages chapter

| Col1          | Algorithm                                | GUI v 3.0 | R package / function |
|--------------|-----------------------------|--------------|--------------|
| Pre-treatment | Fractionnal Airline Model                | yes       |                      |
| Decompsition  | Extended SEATS Fractionnal Airline Model | yes       |                      |
|               | Extended X-11                            | yes       |                      |
|               | Extended STL                             | no        |                      |
| One-Step      | SSF Framework                            | no        |                      |

## Unobserved Components

## Identifying seasonal patterns

### Spectral analysis

### Seasonality tests

## Pre-adjustment

### Calendar correction

generate

### Outliers and intervention variables

add

### Linearization

## Decomposition

### Extended X-11

### Arima Model Based (AMB) Decomposition

### STL decomposition

## State Space framework

one step for pre-treatment and decomp

## Quality assessment 

### Residual seasonality

### Residual Calendar effects
