# JDemetra+ {.unnumbered}

## Introduction

JDemetra+ is an open source software for seasonal adjustment and time series analysis. It has been officially recommended by Eurostat to the European Statistical System members since 2015. It is unique in its combination of very fast Java routines, a graphical user interface and a family of R packages. The graphical interface offers a structured and visual feedback, suitable for refined analysis and training, whereas R tools allow the user to mix the capabilities of JDemetra+ with the versatility of the R world, be it for mathematical functions or data wrangling.

.

link to key references - handbooks (3) - sets of guidelines (2 or 3 ?)

## Version 2.x and version 3

3.0 to be released in December 2022, fills several critical gaps in the tool box of a time series analyst providing extended features for seasonal adjustment and trend estimation, including high frequency data and production tools.


## Main functions

Core JDemetra (java) algorithms can be accessied via several tools:
- Graphical User Interface [GUI](T-graphical-user_interface.qmd)
- ...enhanced with additionnal [plug-ins](T-plug-ins.qmd)
- `R` packages

### Seasonal adjustment algorithms

All are available for low and high frequency data.

| Algorithms               | Access | Key features |
|--------------------------|--------|--------------|
| X13-Arima                |        |              |
| Tramo-Seats              |        |              |
| STL                      |        |              |
| State Space Models (STS) |        |              |

### Temporal Disaggregation and benchmarking

| Algorithms | Access | Key features |
|------------|--------|--------------|
| Chow-lin   |        |              |
| Fernandez  |        |              |
|            |        |              |
|            |        |              |

### Trend-cycle estimation

| Algorithms | Access | Key features |
|------------|--------|--------------|
|            |        |              |
|            |        |              |
|            |        |              |
|            |        |              |

## Nowcasting

| Algorithms | Access | Key features |
|------------|--------|--------------|
|            |        |              |
|            |        |              |
|            |        |              |
|            |        |              |

## Structure of this book

This book is divided in four parts, allowing the user to access the resources from different perspectives.

### Algorithms

This part provides a step by step description of all the algorithms featured in JD+, grouped by purpose - seasonal adjustment - benchmarking - temporal disaggregation - ... links

### Tools

JDemetra+ offers 3 kinds of tools - A Graphical User Interface (GUI) which can be enhanced with plug-ins - A set of R packages - A Cruncher for mass production in seasonal adjustment

### Underlying Statistical Methods

This part gives details about the underlying statistical methods to foster a more in-depth understanding of the algorithms.Those methods are described in the light and spirit of their use as building blocks of the algorithms presented above, not aiming at all at their comprehensive coverage.

## How to use this book

### Audience

This book targets the beginner as well as seasoned methodologist interested in using JDemetra+ software for any the purposes listed below.

The documentation is built in layers allowing to skip details and complexity in the first steps
