# State space modelling {.unnumbered}

## Introduction
State space forms play a central role in JD+. In a first point, we present the model used throughout the library. In a second point, we give an overview of the current implementation. The specificity of the state space framework of JD+ is stressed and the main modules are shortly presented. We finish the document with two examples based on the state space framework of JD+. The first one explains the basic structural models implemented in the "nbdemetra-sa-advanced" plug-in of JD+. The second one shows how the framework can be used to implement time-varying trading days models.



## State space forms (SSF)
     
### General form
The general linear gaussian state-space model can be written in many different ways. The measurement equation and the state equation considered in JD+ 3.0 are presented below.


$$
\begin{array}{r l}
 y_t&= Z_t\alpha_t+\epsilon_t, \quad \epsilon_t \sim\mathcal{N}(0,\sigma^2H_t)\\
\alpha_{t+1}&= T_t\alpha_t+\mu_t,\quad \mu_t\sim\mathcal{N}(0,\sigma^2V_t)
\end{array}
$$

$y_t$ is the observation at period t, $\alpha_t$ is the state vector. $\epsilon_t, \mu_t$ are assumed to be serially independent at all time points and independent between them at all time points. 



The residuals of the state equation will be modelled as
$\mu_t=S_t\xi_t, \quad \xi_t\sim\mathcal{N}(0,\sigma^2I)$.



In other words, $V_t=S_tS_t'$. 



The initial conditions of the filter are defined as follows:

$$\alpha_{-1}=a_{-1}+A_{-1}\delta+\mu_{-1}$$

$$\delta\sim\mathcal{N}(0,\sigma^2\kappa I)$$

$$\mu_{-1}\sim\mathcal{N}(0,\sigma^2P_*)$$

where $\kappa$ is arbitrary large.

$P_*$ is the variance of the stationary part of the initial state vector and models the diffuse part. 



The model used in JD+ is quasi-identical to the model discussed in Durbin-Koopman.



