# Algorithms {.unnumbered #part-A}

This part provides practical guidance for using all the algorithms featured in JDemetra+, be it with the [Graphical User Interface](#t-gui-overview) or [R packages](#t-r-packs)

Further methodological insights on each algorithm can be found in the [Methods](#part-M) part of this book, whereas detailed description of all the available tools allowing to access the algorithms can be found in the [Tools](#part-T) part.

JDemetra+ provides algorithms in the following domains:

Seasonal Adjustment (SA)

- [Seasonal Adjustment overview](#sa-overview)
- [SA: Pre-treatment](#sa-pre-t)
- [SA: X11 decomposition](a-sa-X11)
- [SA: Seats-decomposition](#a-sa-seats)
- [SA: Revision policies](#a-rev-pol)
- [SA: STL decomposition](#a-sa-stl)
- [SA of High-Frequency Data](#a-sa-hf)
- [SA with Basic Stuctural Models (BSM)](#a-sa-bsm)

Modelling and Auxiliary Variables
- [Reg-Arima modelling](#a_reg-a)
- [Outlier detection and external regressors](#a-out-reg-ext)
- [Calendar correction](#a-cal)

Other Algorithms

- [Benchmarking and temporal disaggregation]((#a-bench))
- [Trend-Cycle estimation](#a-trend)
- [Revision analysis](#a-revs)
- [Nowcasting](#a-now)

     
        
