# R packages {#t-r-packs .unnumbered}

## In this chapter

Core JDemetra+ Java algorithms can be accessed in R. This chapter provides an overview of the suite of R packages related to JDemetra+: [rjdverse](https://github.com/rjdverse).

Readme pages, GitHub pages and sometimes vignettes relative to each package provide a detailed description of all available functions: objectives, arguments, output and examples. They are reachable from the [rjdverse](https://github.com/rjdverse) main page.

The corresponding GitHub pages are directly linked to this documentation whenever their use in a selected algorithm is mentioned. More details on specific functions are available in the relevant chapters of the [Algorithm part](#part-A)

## Installing Packages

All R packages related to JDemetra+ (v3.x or v2.x) are available from the [rjdverse Github page](https://github.com/rjdverse).

They can be installed from - GitHub - r-universe - CRAN (for some of them)

As explained in the corresponding Readme files on [Github](https://github.com/rjdverse).

### Configuration needed

-   To run packages based on version 3.x: Java 17 or higher: how to get a portable Java and link it with R on your computer is explained [here](#Rconfig)

-   To run packages based on version 2.x: Java 8 or higher

## Algorithms available in R

### Seasonal adjustment

#### Using JDemetra+ version 3.x

| Algorithm | Package | Comments |
|------------------|------------------|------------------------------------|
| X-13-ARIMA | rjd3x13 | Reg-ARIMA and X-11 decomposition available independently |
| Extended X-11 | rjd3x11plus | Extended for high-frequency (infra-monthly) data and Trend estimation with local polynomial filters |
| Tramo-Seats | rjd3tramoseats | Tramo available independently |
| Extended Tramo | rjd3highfreq | Extended for high-frequency data |
| Extended Seats | rjd3highfreq | Extended for high-frequency data |
| STL+ | rjd3stl | Airline based preadjustment and high-frequency data extension |
| Basic Structural Models | rjd3sts | State space framework |

Version 3.x includes [Revision Policies](#a-rev-pol) in X-13 and Tramo-Seats.

More details on functions parameters and retrieving output in the chapter dedicated to [Seasonal Adjustment](#sa-overview)

#### Using JDemetra+ version 2.x

| Algorithm | Package | Comments |
|------------------|------------------|-------------------------------------|
| X-13-ARIMA | RJDemetra | Reg-ARIMA and X-11 decomposition available independently |
| Tramo-Seats | RJDemetra | Tramo available independently |

### Filtering and Trend estimation

| Algorithm                         | Package                  |
|-----------------------------------|--------------------------|
| Moving average functions          | rjd3filters              |
| Local Polynomial Trend Estimation | rjd3filters, rjd3x11plus |

### Benchmarking

| Algorithm                      | Package   |
|--------------------------------|-----------|
| Denton                         | rjd3bench |
| Cholette                       | rjd3bench |
| Cubic splines                  | rjd3bench |
| GRP (Growth Rate Preservation) | rjd3bench |

### Temporal Disaggregation:

| Algorithm                                   | Package   |
|---------------------------------------------|-----------|
| Chow-Lin, Fernandez and Litterman           | rjd3bench |
| Model-Based Denton                          | rjd3bench |
| Autoregressive Distributed Lag (ADL) models | rjd3bench |
| Reverse regression                          | rjd3bench |
|                                             | rjd3bench |

### Reconciliation and multivariate temporal disaggregation

| Algorithm             | Package   |
|-----------------------|-----------|
| Multivariate Cholette | rjd3bench |

### Calendarization

| Algorithm       | Package   |
|-----------------|-----------|
| Calendarization | rjd3bench |

### Nowcasting

Nowcasting with JDemetra+ is available via the rjd3nowcasting package 

Documentation [here](https://rjdverse.github.io/rjd3nowcasting/)

<!-- algos à detailler -->


<!-- ### Outlier detection  -->

### Revision analysis

Revision analysis on vintages can be performed with rjd3revision package.

Documentation \[here\](<https://rjdverse.github.io/rjd3revisions/>)<https://rjdverse.github.io/rjd3revisions/>

<!-- TO BE ADDED -->

<!-- ## Time series tools {#t-r-packs-tstools} -->

<!-- ### Tests {#t-r-packs-tests} -->

<!-- #### Seasonality tests -->

<!-- #### Tests on residuals -->

## Utility functions available in R

The packages listed below contain utility functions useful when running a seasonal adjustment production process.

### Running the cruncher and generating a quality report

[JDemetra+ cruncher](#t-prod) is an executable module designed for mass production of seasonally adjusted series .

| Package       | JD+ version | Comments                     |
|---------------|-------------|------------------------------|
| rjwsacruncher | 2.x and 3.x | estimation update and output |
| JDCruncheR    | 2.x and 3.x | Quality Report               |

### Wrangling JD+ workspaces

A workspace is a specific JDemetra+ data format (`.xml` files) allowing to use the graphical user interface (GUI) and the cruncher.

| Package | JD+ version | Comments |
|------------------|------------------|------------------------------------|
| rjd3providers | 3.x | manage input files, update metadata |
| rjd3workspace | 3.x | set specifications, open, create, save merge workspaces |
| rjdworkspace | 2.x | idem |

## Building a production process of SA series

rjd3production package is a wrapper with functions encompassing a whole stage of a production process

Documentation [here](https://inseefr.github.io/rjd3production/)

More information on production processes can be found [here](https://saproductionwithjdemetraandr.netlify.app/)

## Generating enhanced output in SA estimation

This additional packages produce enhanced plots and diagnostic outputs.

| Package     | JD+ version | Comments                       |
|-------------|-------------|--------------------------------|
| rjdmarkdown | 2.x         | enhanced print of diagnostics  |
| ggdemetra   | 2.x         | plots based on ggplot2         |
| ggdemetra3  | 3.x         | plots based on ggplot2         |
| rjdqa       | 2.x         | visual dashboard on one series |
