<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>JDemetra+ documentation - Spectral Analysis Principles and Tools</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./M-reg-arima-modelling.html" rel="next">
<link href="./P_Methods.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./P_Methods.html">Methods</a></li><li class="breadcrumb-item"><a href="./M-spectral-analysis.html">Spectral Analysis Principles and Tools</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">JDemetra+ documentation</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/annasmyk/JD_Quarto_Book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is JDemetra+?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./G-how-to-use-this-book.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to use this book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./G-news-v3-vs-v2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">New Features in v 3.x family</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./P_Algorithms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Algorithms</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-RegArima-Tramo-Modelling-Overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modelling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Seasonal Adjustment (SA) Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-pre-treatment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA: Pre-Treatment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-X11-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA: X11 Decomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-seats-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA: Seats Decomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-rev-policies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA: Revision policies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-hf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA of high-frequency data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-x12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA: X12+ and MX12+</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-stl-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA: STL+ and MSTL+</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-sa-bsm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SA: STS and MSTS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-outlier-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Outlier detection and external regressors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-calendar-correction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendar correction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-benchmarking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benchmarking and temporal disagreggation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-trend-cycle-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trend-cycle estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-revision-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Revision Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-nowcasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nowcasting</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./P_Tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tools</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./T-GUI-Overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Graphical User Interface (GUI): Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./T-GUI-Data-Viz-TS-Tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GUI: data visualization and time series tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./T-GUI-SA-Modelling-Features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GUI: SA and Modelling Features</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./T-GUI-Output.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GUI: Generating output</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./T-plug-ins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plug-ins (GUI extensions)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./T-Production-tools-cruncher-QR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cruncher and quality report</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./T-r-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R packages</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./P_Methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-spectral-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Spectral Analysis Principles and Tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-reg-arima-modelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reg-ARIMA models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-X11-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">X11 decomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-SEATS-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Seats decomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-STL-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">STL: Local regression decomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-Temp-Disagg-Bench.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benchmarking and Temporal disaggregation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M-revision-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Revision Analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Output_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Output description</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#in-this-chapter" id="toc-in-this-chapter" class="nav-link active" data-scroll-target="#in-this-chapter">In this chapter</a></li>
  <li><a href="#spectral-analysis-concepts" id="toc-spectral-analysis-concepts" class="nav-link" data-scroll-target="#spectral-analysis-concepts">Spectral analysis concepts</a></li>
  <li><a href="#spectral-density-of-an-arima-model" id="toc-spectral-density-of-an-arima-model" class="nav-link" data-scroll-target="#spectral-density-of-an-arima-model">Spectral density of an ARIMA model</a>
  <ul class="collapse">
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation">Estimation</a></li>
  </ul></li>
  <li><a href="#m-spectral-analysis-m-spectrum-id-peaks" id="toc-m-spectral-analysis-m-spectrum-id-peaks" class="nav-link" data-scroll-target="#m-spectral-analysis-m-spectrum-id-peaks">Identification of spectral peaks</a>
  <ul class="collapse">
  <li><a href="#in-a-tukey-spectrum" id="toc-in-a-tukey-spectrum" class="nav-link" data-scroll-target="#in-a-tukey-spectrum">In a Tukey spectrum</a></li>
  <li><a href="#in-ar-spectrum-definition" id="toc-in-ar-spectrum-definition" class="nav-link" data-scroll-target="#in-ar-spectrum-definition">In AR Spectrum definition</a></li>
  <li><a href="#in-a-periodogram" id="toc-in-a-periodogram" class="nav-link" data-scroll-target="#in-a-periodogram">In a Periodogram</a></li>
  </ul></li>
  <li><a href="#m-spectral-analysis-m-spectrum-graphs" id="toc-m-spectral-analysis-m-spectrum-graphs" class="nav-link" data-scroll-target="#m-spectral-analysis-m-spectrum-graphs">Spectral graphs</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/annasmyk/JD_Quarto_Book/edit/main/M-spectral-analysis.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/annasmyk/JD_Quarto_Book/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="m-spectrum" class="quarto-section-identifier">Spectral Analysis Principles and Tools</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="in-this-chapter" class="level2">
<h2 class="anchored" data-anchor-id="in-this-chapter">In this chapter</h2>
<p>This chapter provides some guidance on spectral analysis, which will allow to understand the principle of various spectral analysis tools available in JDemetra+, via <a href="#t-GUI-tstools-spectral">Graphical User Interface</a> and <a href="T-r-packages.html">R packages</a>.</p>
<ul>
<li><p>explanation of spectral graphs here, but description in GUI chap</p></li>
<li><p>outputs of tests ?</p></li>
<li><p>description of spectral graphs in GUI can be found here</p></li>
</ul>
</section>
<section id="spectral-analysis-concepts" class="level2">
<h2 class="anchored" data-anchor-id="spectral-analysis-concepts">Spectral analysis concepts</h2>
<p>A time series <span class="math inline">\(x_{t}\)</span> with stationary covariance, mean <span class="math inline">\(μ\)</span> and <span class="math inline">\(k^{th}\)</span> autocovariance <span class="math inline">\(E((x_{t}-\mu)(x_{t-k}\mu))=\gamma(k)\)</span> can be described as a weighted sum of periodic trigonometric functions: <span class="math inline">\(sin(\omega t)\)</span> and <span class="math inline">\(cos(\omega t)\)</span>, where <span class="math inline">\(\omega=\frac{2*pi}{T}\)</span> denotes frequency. Spectral analysis investigates this frequency domain representation of <span class="math inline">\(x_{t}\)</span> to determine how important cycles of different frequencies are in accounting for the behaviour of <span class="math inline">\(x_{t}\)</span>.</p>
<p>Assuming that the autocovariances <span class="math inline">\(\gamma(k)\)</span> are absolutely summable(<span class="math inline">\(\sum_{k=-\infty}^{\infty}|\gamma(k)|&lt;\infty\)</span>), the autocovariance generating function, which summarizes these autocovariances through a scalar valued function, is given by <a href="M-tests.html#eq-1">Equation&nbsp;<span>1</span></a> (HAMILTON, J.D. (1994)).</p>
<p><span id="eq-1"><span class="math display">\[
acgf(z)=\sum_{k=-\infty}^{\infty}{z^{k}\gamma(k)}
\tag{1}\]</span></span></p>
<p>where <span class="math inline">\(z\)</span> denotes a complex scalar.</p>
<p>Once the <a href="M-tests.html#eq-1">Equation&nbsp;<span>1</span></a> is divided by <span class="math inline">\(\pi\)</span> and evaluated at some <span class="math inline">\(z{=e}^{-i\omega}=cos\omega-isin\omega\)</span>, where <span class="math inline">\(i=\sqrt{-1}\)</span> and <span class="math inline">\(\omega\)</span> is a real scalar, <span class="math inline">\(-\infty &lt; \ \omega &lt; \infty\)</span>, the result of this transformation is called a population spectrum <span class="math inline">\(f(\omega)\)</span>for <span class="math inline">\(\ x_{t}\)</span>, given in <a href="M-tests.html#eq-2">Equation&nbsp;<span>2</span></a> (HAMILTON, J.D. (1994)).</p>
<p><span id="eq-2"><span class="math display">\[
f(\omega)=\frac{1}{\pi}\sum_{k=-\infty}^{\infty}{e^{-ik\omega}\gamma(k)}
\tag{2}\]</span></span></p>
<p>Therefore, the analysis of the population spectrum in the frequency domain is equivalent to the examination of the autocovariance function in the time domain analysis; however it provides an alternative way of inspecting the process. Because <span class="math inline">\(f(\omega)\text{dω}\)</span> is interpreted as a contribution to the variance of components with frequencies in the range <span class="math inline">\((\omega,\ \omega+d\omega)\)</span>, a peak in the spectrum indicates an important contribution to the variance at frequencies near the value that corresponds to this peak.</p>
<p>As <span class="math inline">\(e^{-i\omega}=cos\omega-isin\omega\)</span>, the spectrum can be also expressed as in <a href="M-tests.html#eq-3">Equation&nbsp;<span>3</span></a>.</p>
<p><span id="eq-3"><span class="math display">\[
f(\omega)=\frac{1}{\pi}\sum_{k=-\infty}^{\infty}{(cos\omega k-isin\omega k)\gamma(k)}
\tag{3}\]</span></span></p>
<p><a href="M-tests.html#eq-3">Equation&nbsp;<span>3</span></a> can be presented as:</p>
<p><span id="eq-4"><span class="math display">\[
f(\omega)=\frac{1}{\pi}[\ \gamma(0)+2\sum_{k=1}^{\infty}{\ \gamma(k)}cos\text{ωk}]
\tag{4}\]</span></span></p>
<p>This implies that if autocovariances are absolutely summable the population spectrum exists and is a continuous, real-valued function of <span class="math inline">\(\omega\)</span>. Due to the properties of trigonometric functions <span class="math inline">\((\cos(-\omega k)=\cos(\text{ωk})\)</span> and <span class="math inline">\(\cos(\omega+2\pi j)k=cos(\omega k))\)</span> the spectrum is a periodic, even function of <span class="math inline">\(\omega\)</span>, symmetric around <span class="math inline">\(\omega=0\)</span>. Therefore, the analysis of the spectrum can be reduced to the interval <span class="math inline">\((-\pi,\pi)\)</span>. The spectrum is non-negative for all <span class="math inline">\(\omega \in (-\pi,\pi)\)</span>.</p>
<p>The shortest cycle that can be distinguished in a time series lasts two periods. The frequency which corresponds to this cycle is <span class="math inline">\(\omega=\pi\)</span> and is called the Nyquist frequency. The frequency of the longest cycles that can be observed in the time series with <span class="math inline">\(n\)</span> observations is <span class="math inline">\(\omega=\frac{2\pi}{n}\)</span> and is called the fundamental (Fourier) frequency.</p>
<p>Note that if <span class="math inline">\(x_{t}\)</span> is a white noise process with zero mean and variance <span class="math inline">\(\sigma^{2}\)</span>, then for all <span class="math inline">\(|k|&gt; 0\)</span> <span class="math inline">\(\gamma(k)=0\)</span> and the spectrum of <span class="math inline">\(x_{t}\)</span> is constant (<span class="math inline">\(f(\omega)=\frac{\sigma^{2}}{\pi}\)</span>) since each frequency in the spectrum contributes equally to the variance of the process (BROCKWELL, P.J., and DAVIS, R.A. (2002)).</p>
<p>The aim of spectral analysis is to determine how important cycles of different frequencies are in accounting for the behaviour of a time series. Since spectral analysis can be used to detect the presence of periodic components, it is a natural diagnostic tool for detecting trading day effects as well as seasonal.</p>
<p>Among the tools used for spectral analysis are the autoregressive spectrum and the periodogram.</p>
<p>The explanations given in the subsections of this node derive mainly from DE ANTONIO, D., and PALATE, J. (2015) and BROCKWELL, P.J., and DAVIS, R.A. (2006).</p>
</section>
<section id="spectral-density-of-an-arima-model" class="level2">
<h2 class="anchored" data-anchor-id="spectral-density-of-an-arima-model">Spectral density of an ARIMA model</h2>
<section id="estimation" class="level3">
<h3 class="anchored" data-anchor-id="estimation">Estimation</h3>
<section id="m-spectral-analysis-m-spectrum-periodogram" class="level4">
<h4 class="anchored" data-anchor-id="m-spectral-analysis-m-spectrum-periodogram">Method 1: Periodogram</h4>
<p>For any given frequency <span class="math inline">\(\omega\)</span> the sample periodogram is the sample analog of the sample spectrum. In general, the periodogram is used to identify the periodic components of unknown frequency in the time series. X-13ARIMA-Seats and Tramo-Seats use this tool for detecting seasonality in raw time series and seasonally adjusted series. Apart from this it is applied for checking randomness of the residuals from the ARIMA model.</p>
<p>To define a periodogram, first consider a vector of complex numbers</p>
<p><span id="eq-5"><span class="math display">\[
\mathbf{x}=\begin{bmatrix}
  x_{1} \\
  x_{2} \\
  . \\
  . \\
  . \\
  x_{n} \\
  \end{bmatrix} \in \mathbb{C}^{n}
\tag{5}\]</span></span></p>
<p>where <span class="math inline">\(\mathbb{C}^{n}\)</span> is the set of all column vectors with complex-valued components.</p>
<p>The Fourier frequencies associated with the sample size <span class="math inline">\(n\)</span> are defined as a set of values <span class="math inline">\(ω_{j}=\frac{2\pi j}{n}\)</span>, <span class="math inline">\(j=-[\frac{n-1}{2}],\ldots,[\frac{n}{2}]\)</span>, <span class="math inline">\(-\pi&lt; \omega_{j} \leq \pi\)</span>, <span class="math inline">\(j\in F_{n}\)</span>, where <span class="math inline">\({[n]}\)</span> denotes the largest integer less than or equal to <span class="math inline">\(n\)</span>. The Fourier frequencies, which are called harmonics, are given by integer multiples of the fundamental frequency <span class="math inline">\(\ \frac{2\pi}{n}\)</span>.</p>
<p>Now the <span class="math inline">\(n\)</span> vectors <span class="math inline">\(e_{j}=n^{-\frac{1}{2}}(e^{-i\omega_{j}},e^{-i{2\omega}_{j}},\ldots,e^{-inω_{j}})^{'}\)</span> can be defined. Vectors <span class="math inline">\(e_{1},\ldots, e_{n}\)</span> are orthonormal in the sense that:</p>
<p><span id="eq-6"><span class="math display">\[
{\mathbf{e}_{j}^{*}\mathbf{e}}_{k}=n^{-1}\sum_{r=1}^{n}e^{ir(\omega_{j}-\omega_{k})}={ \begin{matrix}
1,\ if\ j=k \\
0,\ if\ j \neq k \\
\end{matrix}}
\tag{6}\]</span></span></p>
<p>where <span class="math inline">\(\mathbf{e}_{j}^{*}\)</span> denotes the row vector, which <span class="math inline">\(k^{th}\)</span> component is the complex conjugate of the <span class="math inline">\(k^{th}\)</span> component of <span class="math inline">\(\mathbf{e}_{j}\)</span>. These vectors are a basis of <span class="math inline">\(F_{n}\)</span>, so that any <span class="math inline">\(\mathbf{x}\in\mathbb{C}^{n}\)</span> can be expressed as a sum of <span class="math inline">\(n\)</span> components:</p>
<p><span id="eq-7"><span class="math display">\[
\mathbf{x}=\sum_{j=-[\frac{n-1}{2}]}^{[\frac{n}{2}]}{a_{j}\mathbf{e}_{j}}
\tag{7}\]</span></span></p>
<p>where the coefficients <span class="math inline">\(a_{j}=\mathbf{e}_{j}^{*}\mathbf{x}=n^{-\frac{1}{2}}\sum_{t=1}^{n}x_{t}e^{-it\omega_{j}}\)</span> are derived from <a href="M-SEATS-decomposition.html#eq-7">Equation&nbsp;<span>7</span></a> by multiplying the equation on the left by <span class="math inline">\(\mathbf{e}_{j}^{*}\)</span> and using <a href="M-SEATS-decomposition.html#eq-5">Equation&nbsp;<span>5</span></a>.</p>
<p>The sequence of <span class="math inline">\(\{a_{j},j\in F_{n}\}\)</span> is referred as a discrete Fourier transform of <span class="math inline">\(\mathbf{x}\mathbb{\in C}^{n}\)</span> and the periodogram <span class="math inline">\(I(\omega_{j})\)</span> of <span class="math inline">\(\mathbf{x}\)</span> at Fourier frequency <span class="math inline">\(\omega_{j}=\frac{2\pi j}{n}\)</span> is defined as the square of the Fourier transform <span class="math inline">\(\{a_{j}\}\)</span> of <span class="math inline">\(\mathbf{x}\)</span>:</p>
<p><span id="eq-8"><span class="math display">\[
{I(\omega_{j})\mathbf{=}{|a_{j} |^{2}}_{\ }=n^{-\ 1}|\sum_{t=1}^{n}x_{t}e^{-it\omega_{j}} |^{2}}_{\mathbf{\ }}
\tag{8}\]</span></span></p>
<p>From <a href="M-SEATS-decomposition.html#eq-6">Equation&nbsp;<span>6</span></a> and <a href="M-SEATS-decomposition.html#eq-7">Equation&nbsp;<span>7</span></a> it can be shown that a periodogram decomposes the total sum of squares <span class="math inline">\(\sum_{t=1}^{n}|x_{t} |^{2}\)</span> into a sum of components associated with the Fourier frequencies <span class="math inline">\(ω_{j}\)</span>:</p>
<p><span id="eq-9"><span class="math display">\[
\sum_{t=1}^{n}{|x_{t}|}^{2}=\sum_{j=-[\frac{n-1}{2}]}^{[\frac{n}{2}]}|a_{j}|^{2}=\sum_{j=-[\frac{n-1}{2}]}^{[\frac{n}{2}]}{I(\omega_{j})}
\tag{9}\]</span></span></p>
<p>If <span class="math inline">\(\ \mathbf{x\  \in}\ {R}^{n}\)</span>, <span class="math inline">\(\omega_{j}\)</span> and <span class="math inline">\({-\omega}_{j}\)</span> are both in <span class="math inline">\([-\pi,-\pi]\)</span> and <span class="math inline">\(a_{j}\)</span> is presented in its polar form (i.e.&nbsp;<span class="math inline">\(a_{j}=r_{j}\exp(i\theta_{j})\)</span>), where <span class="math inline">\(r_{j}\)</span> is the modulus of <span class="math inline">\(a_{j}\)</span>, then <a href="M-SEATS-decomposition.html#eq-7">Equation&nbsp;<span>7</span></a> can be rewritten in the form:</p>
<p><span id="eq-10"><span class="math display">\[
\mathbf{x}=a_{0}\mathbf{e}_{0}+\sum_{j=1}^{[\frac{n-1}{2}]}{ {2^{1/2}r}_{j}{(\mathbf{c}}_{j}\cos\theta_{j}{-\mathbf{s}}_{j}\sin\theta_{j})+a_{n/2}\mathbf{e}_{n/2}}
\tag{10}\]</span></span></p>
<p>The orthonormal basis for <span class="math inline">\({R}^{n}\)</span> is <span class="math inline">\(\{\mathbf{e}_{0},\mathbf{c}_{1},\mathbf{s}_{1},\ldots,\mathbf{c}_{[\frac{n-1}{2}]},\mathbf{s}_{[\frac{n-1}{2}]},\mathbf{e}_{\frac{n}{2}(excluded\ if\ n\ is\ odd)}\}\)</span>, where:</p>
<p><span class="math inline">\(\mathbf{e}_{0}\)</span> is a vector composed of n elements equal to <span class="math inline">\(n^{-1/2}\)</span>, which implies that <span class="math inline">\(\mathbf{a}_{0}\mathbf{e}_{0}={(n^{-1}\sum_{t=1}^{n}x_{t},\ldots,n^{-1}\sum_{t=1}^{n}x_{t})}^{'}\)</span>;</p>
<p><span class="math display">\[
\mathbf{c}_{j}=(\frac{n}{2})^{-1/2}{(\cos\omega_{j},\cos{2\omega}_{j},\ldots,\cos{n\omega_{j}})}^{'}, for 1 \leq j \leq [\frac{(n-1)}{2}]
\]</span></p>
<p><span class="math display">\[
\mathbf{s}_{j}={(\frac{n}{2})}^{-1/2}{(\sin{\omega_{j}},\sin{2\omega_{j}},\ldots,\sin{n\omega_{j}})}^{'},\ for\ 1 \leq j \leq [\frac{(n-1)}{2}]
\]</span></p>
<p><span class="math display">\[
\mathbf{e}_{n/2}={(-(n^{-\frac{1}{2}}),n^{-\frac{1}{2}},\ldots,{-(n)}^{-\frac{1}{2}}),n^{-\frac{1}{2}})}^{'}
\]</span></p>
<p><a href="M-SEATS-decomposition.html#eq-9">Equation&nbsp;<span>9</span></a> can be seen as an OLS regression of <span class="math inline">\(x_{t}\)</span> on a constant and the trigonometric terms. As the vector of explanatory variables includes <span class="math inline">\(n\)</span> elements, the number of explanatory variables in <a href="M-SEATS-decomposition.html#eq-9">Equation&nbsp;<span>9</span></a> is equal to the number of observations. HAMILTON, J.D. (1994) shows that the explanatory variables are linearly independent, which implies that an OLS regression yields a perfect fit (i.e.&nbsp;without an error term). The coefficients have the form of a simple OLS projection of the data on the orthonormal basis:</p>
<p><span id="eq-11"><span class="math display">\[
\widehat{a}_{0}=\frac{1}{\sqrt{n}}\sum_{t=1}^{n}x_{t}
\tag{11}\]</span></span></p>
<p><span id="eq-12"><span class="math display">\[
\widehat{a}_{n/2}=\frac{1}{\sqrt{n}}\sum_{t=1}^{n}{(-1)}^{t}x_{t}(  \text{only when n is even})
\tag{12}\]</span></span></p>
<p><span id="eq-13"><span class="math display">\[
\widehat{a}_{0}=\frac{1}{\sqrt{n}}\sum_{t=1}^{n}x_{t}
\tag{13}\]</span></span></p>
<p><span id="eq-14"><span class="math display">\[
{\widehat{\alpha}}_{j}=2^{1/2}r_{j}\cos{\theta_{j}}={(\frac{n}{2})}^{-1/2}\sum_{t=1}^{n}x_{t}\cos{(t\frac{2\pi j}{n})}, j  =1,\ldots,[\frac{n-1}{2}]
\tag{14}\]</span></span></p>
<p><span id="eq-15"><span class="math display">\[
{\widehat{\beta}}_{j}=2^{1/2}r_{j}\sin{\theta_{j}}={(\frac{n}{2})}^{-1/2}\sum_{t=1}^{n}x_{t}\sin{(t\frac{2\pi j}{n})}, j=1,\ldots,[\frac{n-1}{2}]
\tag{15}\]</span></span></p>
<p>With <a href="M-SEATS-decomposition.html#eq-9">Equation&nbsp;<span>9</span></a> the total sum of squares <span class="math inline">\(\sum_{t=1}^{n}|x_{t} |^{2}\)</span> can be decomposed into <span class="math inline">\(2 \times [\frac{n-1}{2}]\)</span> components corresponding to <span class="math inline">\(\mathbf{c}_{j}\)</span> and <span class="math inline">\(\mathbf{s}_{j}\)</span>, which are grouped to produce the “frequency <span class="math inline">\(ω_{j}\)</span>” component for <span class="math inline">\(1 \geq j \geq [\frac{n-1}{2}]\)</span>. As it is shown in the table below, the value of the periodogram at the frequency <span class="math inline">\(\omega_{j}\)</span> is the contribution of the <span class="math inline">\(j^{\text{th}}\)</span> harmonic to the total sum of squares <span class="math inline">\(\sum_{t=1}^{n}|x_{t} |^{2}\)</span>.</p>
<p><strong>Decomposition of sum of squares into components corresponding to the harmonics</strong></p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 25%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Frequency</strong></th>
<th><strong>Degrees of freedom</strong></th>
<th><strong>Sum of squares decomposition</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\omega_{0}\)</span> (mean)</td>
<td>1</td>
<td><span class="math inline">\({a_{0}^{2}}_{\ }=n^{-1}(\sum_{t=1}^{n}x_{t})^{2}=I(0)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\omega_{1}\)</span></td>
<td>2</td>
<td><span class="math inline">\({2r_{1}^{2}}_{\ }=2{|a_{1}|}^{2}=2I(\omega_{1})\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\omega_{k}\)</span></td>
<td>2</td>
<td><span class="math inline">\({2r_{k}^{2}}_{\ }=2{|a_{k}|}^{2}=2I(\omega_{k})\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\omega_{n/2}=\pi\)</span> (excluded if <span class="math inline">\(n\)</span> is odd)</td>
<td>1</td>
<td><span class="math inline">\(a_{n/2}^{2}=I(\pi)\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><span class="math inline">\(\mathbf{n}\)</span></td>
<td><span class="math inline">\(\sum_{\mathbf{t=1}}^{\mathbf{n}}\mathbf{x}_{\mathbf{t}}^{\mathbf{2}}\)</span></td>
</tr>
</tbody>
</table>
<p>Source: DE ANTONIO, D., and PALATE, J. (2015).</p>
<p>Obviously, if series were random then each component <span class="math inline">\(I(\omega_{j})\)</span> would have the same expectation. On the contrary, when the series contains a systematic sine component having a frequency <span class="math inline">\(j\)</span> and amplitude <span class="math inline">\(A\)</span> then the sum of squares <span class="math inline">\(I(\omega_{j})\)</span> increases with <span class="math inline">\(A\)</span>. In practice, it is unlikely that the frequency <span class="math inline">\(j\)</span> of an unknown systematic sine component would exactly match any of the frequencies, for which periodogram have been calculated. Therefore, the periodogram would show an increase in intensities in the immediate vicinity of <span class="math inline">\(j\)</span>. (BOX, G.E.P., JENKINS, G.M., and REINSEL, G.C. (2007).</p>
<p>Note that in JDemetra+ the periodogram object corresponds exactly to the contribution to the sum of squares of the standardised data, since the series are divided by their standard deviation for computational reasons.</p>
<p>Using the decomposition presented in table above the periodogram can be expressed as:</p>
<p><span id="eq-16"><span class="math display">\[
I(\omega_{j})\mathbf{=}\begin{matrix}r_{j}^{2}=\frac{1}{2}{(\alpha}_{j}^{2}+\beta_{j}^{2})=\ {\frac{1}{n}(\sum_{t=1}^{n}{x_{t}\cos{({t\frac{2\pi j}{n}}_{\ })\ }})}^{2}+\frac{1}{n}(\sum_{t=1}^{n}{x_{t}\sin(t\frac{2\pi j}{n})_{\ }})^{2} \\
\end{matrix}
\tag{16}\]</span></span></p>
<p>where <span class="math inline">\(j=0,\ldots,[\frac{n}{2}]\)</span>.</p>
<p>Since <span class="math inline">\(\mathbf{x}-\overline{\mathbf{x}}\)</span> are generated by an orthonormal basis, and <span class="math inline">\(\overline{\mathbf{x}}\mathbf{=}a_{0}\mathbf{e}_{0}\)</span> <a href="M-SEATS-decomposition.html#eq-9">Equation&nbsp;<span>9</span></a> can be rearranged to show that the sum of squares is equal to the sum of the squared coefficients:</p>
<p><span id="eq-17"><span class="math display">\[
\mathbf{x}-a_{0}\mathbf{e}_{0}=\sum_{j=1}^{[(n-1)/2]}(\alpha_{j}\mathbf{c}_{j}+\beta_{j}\mathbf{s}_{j})+a_{n/2}\mathbf{e}_{n/2}
\tag{17}\]</span></span></p>
<p>Thus the sample variance of <span class="math inline">\(x_{t}\)</span> can be expressed as:</p>
<p><span id="eq-18"><span class="math display">\[
n^{-1}\sum_{t=1}^{n}{(x_{t}-\overline{x})}^{2}=n^{-1}(\sum_{k=1}^{[(n-1)/2]}2{r_{j}}^{2}
+{a_{n/2}}^{2})
\tag{18}\]</span></span></p>
<p>where <span class="math inline">\(a_{n/2}^{2}\)</span> is excluded if <span class="math inline">\(n\)</span> is odd.</p>
<p>The term <span class="math inline">\(2{r_{j}}^{2}\)</span> in <a href="M-SEATS-decomposition.html#eq-18">Equation&nbsp;<span>18</span></a> is then the contribution of the <span class="math inline">\(j^{\text{th}}\)</span> harmonic to the variance and <a href="M-SEATS-decomposition.html#eq-18">Equation&nbsp;<span>18</span></a> shows then how the total variance is partitioned.</p>
<p>The periodogram ordinate <span class="math inline">\(I(\omega_{j})\)</span> and the autocovariance coefficient <span class="math inline">\(\gamma(k)\)</span> are both quadratic forms of <span class="math inline">\(x_{t}\)</span>. It can be shown that the periodogram and autocovariance function are related and the periodogram can be written in terms of the sample autocovariance function for any non-zero Fourier frequency <span class="math inline">\(ω_{j}\)</span> (The proof is given in BROCKWELL, P.J., and DAVIS, R.A. (2006)).</p>
<p><span id="eq-19"><span class="math display">\[
I(\omega_{j})=\sum_{|k |&lt; n}^{\ }{\widehat{\gamma}(k)}_{\ }e^{-ik\omega_{j}}={\widehat{\gamma}(0)}_{\ }+2\sum_{k=1}^{n-1}{\widehat{\gamma}(k)\cos{(k\omega_{j})}}_{\ }
\tag{19}\]</span></span></p>
<p>and for the zero frequency <span class="math inline">\(\ I(0)=n|\overline{x}|^{2}\)</span>.</p>
<p>Once comparing <a href="M-SEATS-decomposition.html#eq-19">Equation&nbsp;<span>19</span></a> with an expression of the spectral density of a stationary process:</p>
<p><span id="eq-20"><span class="math display">\[
f(\omega_{\ })=\frac{1}{2\pi}\sum_{k &lt;-\infty}^{\infty}{\gamma(k)}_{\ }e^{-ik\omega_{\ }}=\frac{1}{2\pi}[{\gamma(0)}_{\ }+2(\sum_{k=1}^{\infty}{\gamma(k)\cos{(k\omega_{\ })}})]
\tag{20}\]</span></span></p>
<p>It can be noticed that a periodogram is a sample analogue of the population spectrum. In fact, it can be shown that the periodogram is asymptotically unbiased but inconsistent estimator of the population spectrum <span class="math inline">\(f(\omega)\)</span>. Therefore, the periodogram is a wildly fluctuating, with high variance, estimate of the spectrum. However, the consistent estimator can be achieved by applying the different linear smoothing filters to the periodogram, called lag-window estimators. The lag-window estimators implemented in JDemetra+ includes square, Welch, Tukey, Barlett, Hanning and Parzen. They are described in DE ANTONIO, D., and PALATE, J. (2015). Alternatively, the model-based consistent estimation procedure, resulting in autoregressive spectrum estimator, can be applied.</p>
</section>
<section id="m-spectral-analysis-m-spectrum-ar-est" class="level4">
<h4 class="anchored" data-anchor-id="m-spectral-analysis-m-spectrum-ar-est">Method 2: Autoregressive spectrum estimation</h4>
<p>BROCKWELL, P.J., and DAVIS, R.A. (2006) point out that for any real-valued stationary process <span class="math inline">\((x_{t})\)</span> with continuous spectral density <span class="math inline">\(f(\omega)\)</span> it is possible to find both <span class="math inline">\(AR(p)\)</span> and <span class="math inline">\(MA(q)\)</span> processes which spectral densities are arbitrarily close to <span class="math inline">\(f(\omega)\)</span>. For this reason, in some sense, <span class="math inline">\((x_{t})\)</span> can be approximated by either <span class="math inline">\(AR(p)\)</span> or <span class="math inline">\(MA(q)\)</span> process. This fact is a basis of one of the methods of achieving a consistent estimator of the spectrum, which is called an autoregressive spectrum estimation. It is based on the approximation of the stochastic process <span class="math inline">\((x_{t})\)</span> by an autoregressive process of sufficiently high order <span class="math inline">\(p\)</span>:</p>
<p><span id="eq-21"><span class="math display">\[
x_{t}=\mu+(\phi_{1}B+\ldots+\phi_{p}B^{p})x_{t}+\varepsilon_{t}
\tag{21}\]</span></span></p>
<p>where <span class="math inline">\(\varepsilon_{t}\)</span> is a white-noise variable with mean zero and a constant variance.</p>
<p>The autoregressive spectrum estimator for the series <span class="math inline">\(x_{t}\)</span> is defined as (Definition from ‘<em>X-12-ARIMA Reference Manual</em>’ (2011)).</p>
<p><span id="eq-22"><span class="math display">\[
\widehat{s}(\omega)=10\operatorname{\times}{\log_{10}\frac{\sigma_{x}^{2}}{2\pi{|1-\sum_{k=1}^{p}{\widehat{\phi}}_{k}e^{-ik\omega}|}^{2}}}
\tag{22}\]</span></span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(\omega\)</span>– frequency, <span class="math inline">\(0 \leq \omega \leq \pi\)</span>;</p></li>
<li><p><span class="math inline">\(\sigma_{x}^{2}\)</span> innovation variance of the sample residuals;</p></li>
<li><p><span class="math inline">\(\widehat{\phi}_{k}\)</span>–<span class="math inline">\(\text{AR}(k)\)</span> coefficient estimates of the linear regression of <span class="math inline">\(x_{t}-\overline{x}\)</span> on <span class="math inline">\(x_{t-k}-\overline{x}\)</span>, <span class="math inline">\(1 \leq k \leq p\)</span>.</p></li>
</ul>
<p>The autoregressive spectrum estimator is used in the visual spectral analysis tool for detecting significant peaks in the spectrum. The criterion of <em>visual significance</em>, implemented in JDemetra+, is based on the range <span class="math inline">\({\widehat{s}}^{\max}-{\widehat{s}}^{\min}\)</span> of the <span class="math inline">\(\widehat{s}(\omega)\)</span> values, where <span class="math inline">\({\widehat{s}}^{\max}=\max_{k}\widehat{s}(\omega_{k})\)</span>; <span class="math inline">\({\widehat{s}}^{\min}=\min_{k}\widehat{s}(\omega_{k});\)</span> and <span class="math inline">\(\widehat{s}(\omega_{k})\)</span> is <span class="math inline">\(k^{\text{th}}\)</span> value of autoregressive spectrum estimator.</p>
<p>A particular value is considered to be visually significant if, at a trading day or at a seasonal frequency <span class="math inline">\(\omega_{k}\)</span> (other than the seasonal frequency <span class="math inline">\(\omega_{60}=\pi\)</span>), <span class="math inline">\(\widehat{s}(\omega_{k})\)</span> is above the median of the plotted values of <span class="math inline">\(\widehat{s}(\omega_{k})\)</span> and is larger than both neighbouring values <span class="math inline">\(\widehat{s}(\omega_{k-1})\)</span> and <span class="math inline">\(\widehat{s}(\omega_{k+1})\)</span> by at least <span class="math inline">\(\frac{6}{52}\)</span> times the range <span class="math inline">\({\widehat{s}}^{\max}-{\widehat{s}}^{\min}\)</span>.</p>
<p>Following the suggestion of SOUKUP, R.J., and FINDLEY, D.F. (1999), JDemetra+ uses an autoregressive model spectral estimator of model order 30. This order yields high resolution of strong components, meaning peaks that are sharply defined in the plot of <span class="math inline">\(\widehat{s}(\omega)\)</span> with 61 frequencies. The minimum number of observations needed to compute the spectrum is set to <span class="math inline">\(n=80\)</span> for monthly data and to <span class="math inline">\(n=60\)</span> for quarterly series while the maximum number of observations considered for the estimation is 121. Consequently, with these settings it is possible to identify up to 30 peaks in the plot of 61 frequencies. By choosing <span class="math inline">\(\omega_{k}=\frac{\text{πk}}{60}\)</span> for <span class="math inline">\(k=0,1,...,60\)</span> the density estimates are calculated at exact seasonal frequencies (1, 2, 3, 4, 5 and 6 cycles per year).</p>
<p>The model order can also be selected based on the AIC criterion (in practice it is much lower than 30). A lower order produces the smoother spectrum, but the contrast between the spectral amplitudes at the trading day frequencies and neighbouring frequencies is weaker, and therefore not as suitable for automatic detection.</p>
<p>SOUKUP, R.J., and FINDLEY, D.F. (1999) also explain that the periodogram can be used in the <em>visual significance</em> test as it has as good as those of the AR(30) spectrum abilities to detect trading day effect, but also has a greater false alarm rate, which is defined as the fraction of the 50 replicates for which a visually significant spectral peak occurred at one of the trading day frequencies being considered in the designated output spectra (SOUKUP, R.J., and FINDLEY, D.F. (1999)).</p>
</section>
<section id="m-spectral-analysis-m-spectrum-tuckey" class="level4">
<h4 class="anchored" data-anchor-id="m-spectral-analysis-m-spectrum-tuckey">Method 3: Tukey spectrum</h4>
<p>The Tukey spectrum belongs to the class of lag-window estimators. A lag window estimator of the spectral density <span class="math inline">\(f(\omega)=\frac{1}{2\pi}\sum_{k&lt;-\infty}^{\infty}\gamma(k)e^{i k \omega}\)</span> is defined as follows:</p>
<p><span class="math display">\[
\hat{f}_{L}(\omega)=\frac{1}{2\pi}\sum_{|h|\leq r} w(h/r)\hat{\gamma}(h)e^{i h \omega}
\]</span></p>
<p>where <span class="math inline">\(\hat{\gamma}(.)\)</span> is the sample autocovariance function, <span class="math inline">\(w(.)\)</span> is the lag window, and <span class="math inline">\(r\)</span> is the truncation lag. <span class="math inline">\(|w(x)|\)</span> is always less than or equal to one, <span class="math inline">\(w(0)=1\)</span> and <span class="math inline">\(w(x)=0\)</span> for <span class="math inline">\(|x|&gt; 1\)</span>. The simple idea behind this formula is to down-weight the autocovariance function for high lags where <span class="math inline">\(\hat{\gamma}(h)\)</span> is more unreliable. This estimator requires choosing <span class="math inline">\(r\)</span> as a function of the sample size such that <span class="math inline">\(r/narrow 0\)</span> and <span class="math inline">\(r\rightarrow \infty\)</span> when <span class="math inline">\(narrow \infty\)</span> . These conditions guarantee that the estimator converges to the true density.</p>
<p>JDemetra+ implements the so-called Blackman-Tukey (or Tukey-Hanning) estimator, which is given by <span class="math inline">\(w(h/r)=0.5(1+cos(\pi h/r))\)</span> if <span class="math inline">\(|h/r|\leq 1\)</span> and <span class="math inline">\(0\)</span> otherwise.</p>
<p>The choice of large truncation lags <span class="math inline">\(r\)</span> decreases the bias, of course, but it also increases the variance of the spectral estimate and decreases the bandwidth.</p>
<p>JDemetra+ allows the user to modify all the parameters of this estimator, including the window function.</p>
</section>
</section>
</section>
<section id="m-spectral-analysis-m-spectrum-id-peaks" class="level2">
<h2 class="anchored" data-anchor-id="m-spectral-analysis-m-spectrum-id-peaks">Identification of spectral peaks</h2>
<p>The sections below describe the test, their practical implementation in the Graphical User interface can be found <a href="">here</a></p>
<p>In order to decide whether a series has a seasonal component that is predictable (stable) enough, these tests use visual criteria and formal tests for the periodogram. The periodogram is calculated using complete years, so that the set of Fourier frequencies contains exactly all seasonal frequencies.</p>
<p>The tests rely on two basic principles:</p>
<ul>
<li><p>The peaks associated with seasonal frequencies should be larger than the median spectrum for all frequencies and;</p></li>
<li><p>The peaks should exceed the spectrum of the two adjacent values by more than a critical value.</p></li>
</ul>
<p>JDemetra+ performs this test on the original series. If these two requirements are met, the test results are displayed in green. The statistical significance of each of the seasonal peaks (i.e.&nbsp;frequencies <span class="math inline">\(\frac{\pi}{6},\ \frac{\pi}{3},\ \frac{\pi}{2},\ \frac{2\pi}{3}\)</span> and <span class="math inline">\(\frac{5\pi}{6}\)</span> corresponding to 1, 2, 3, 4 and 5 cycles per year) is also displayed. The seasonal and trading days frequencies depends on the frequency of time series. They are shown in the table below. The symbol <span class="math inline">\(d\)</span> denotes a default frequency and is described below the table.</p>
<p><strong>The seasonal and trading day frequencies by time series frequency</strong></p>
<table class="table">
<colgroup>
<col style="width: 32%">
<col style="width: 32%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Number of months per period (year)</strong></th>
<th><strong>Seasonal frequency</strong></th>
<th><strong>Trading day frequency (radians)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>12</td>
<td><span class="math inline">\(\frac{\pi}{6},\frac{\pi}{3},\ \frac{\pi}{2},\frac{2\pi}{3},\ \frac{5\pi}{6},\ \pi\)</span></td>
<td><span class="math inline">\(d\)</span>,2.714</td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(\frac{\pi}{2}\)</span>, <span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(d\)</span>, 1.292, 1.850, 2.128</td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(d\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(d\)</span></td>
</tr>
</tbody>
</table>
<p>The calendar (trading day or working day) effects, related to the variation in the number of different days of the week per period, can induce periodic patterns in the data that can be similar to those resulting from pure seasonal effects. From the theoretical point of view, trading day variability is mainly due to the fact that the average number of days in the months or quarters is not equal to a multiple of 7 (the average number of days of a month in the year of 365.25 days is equal to <span class="math inline">\(\frac{365.25}{12}=30.4375\)</span> days). This effect occurs <span class="math inline">\(\frac{365.25}{12} \times \frac{1}{7}=4.3482\)</span> times per month: one time for each one of the four complete weeks of each month, and a residual of 0.3482 cycles per month, i.e.&nbsp;<span class="math inline">\(0.3482 \times 2\pi=2.1878\)</span> radians. This turns out to be a fundamental frequency for the effects associated with monthly data. In JDemetra+ the fundamental frequency corresponding to 0.3482 cycles per month is used in place of the closest frequency <span class="math inline">\(\frac{\text{πk}}{60}\)</span>. Thus, the quantity <span class="math inline">\(\frac{\pi \times 42}{60}\)</span> is replaced by <span class="math inline">\(\omega_{42}=0.3482 \times 2\pi=2.1878\)</span>. The frequencies neighbouring <span class="math inline">\(\omega_{42}\)</span>, i.e.&nbsp;<span class="math inline">\(\omega_{41}\)</span> and <span class="math inline">\(\omega_{43}\)</span> are set to, respectively, <span class="math inline">\(2.1865-\frac{1}{60}\)</span> and <span class="math inline">\(2.1865+\frac{1}{60}\)</span>.</p>
<p>The default frequencies (<span class="math inline">\(d\)</span>) for calendar effect are: 2.188 (monthly series) and 0.280 (quarterly series). They are computed as:</p>
<p><span id="eq-23"><span class="math display">\[
\omega_{\text{ce}}=\frac{2\pi}{7}(n-7 \times [\frac{n}{7}])
\tag{23}\]</span></span></p>
<p>where <span class="math inline">\(n=\frac{365.25}{s}\)</span>, <span class="math inline">\(s=4\)</span> for quarterly series and <span class="math inline">\(s=12\)</span> for monthly series.</p>
<p>Other frequencies that correspond to trading day frequencies are: 2.714 (monthly series) and 1.292, 1.850, 2.128 (quarterly series).</p>
<p>In particular, the calendar frequency in monthly data (marked in red on the figure below) is very close to the seasonal frequency corresponding to 4 cycles per year <span class="math inline">\(\text{ω}_{40}=\frac{2}{3}\pi=2.0944\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="All_images/UG_A_image19.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><strong>Periodogram with seasonal (grey) and calendar (red) frequencies highlighted</strong></figcaption>
</figure>
</div>
<p>This implies that it may be hard to disentangle both effects using the frequency domain techniques.</p>
<section id="in-a-tukey-spectrum" class="level3">
<h3 class="anchored" data-anchor-id="in-a-tukey-spectrum">In a Tukey spectrum</h3>
<p>Current JDemetra+ implementation of the seasonality test is based on a <span class="math inline">\(F(d_{1},d_{2})\)</span> approximation that has been originally proposed by Maravall (2012) for Tramo-Seats. This test is has been designed for a Blackman-Tukey window based on a particular choices of the truncation lag <span class="math inline">\(r\)</span> and sample size. Following this approach, we determine visually significant peaks for a frequency <span class="math inline">\(\omega_{j}\)</span> when</p>
<p><span class="math display">\[
\frac{2 f_{x}(\omega_{j})}{[f_{x}(\omega_{j+1})+ f_{x}(\omega_{j-1})]} \ge CV(\omega_{j})
\]</span></p>
<p>where <span class="math inline">\(CV(\omega_{j})\)</span> is the critical value of a <span class="math inline">\(F(d_{1},d_{2})\)</span> distribution, where the degrees of freedom are determined using simulations. For <span class="math inline">\(\omega_{j}=\pi\)</span>, we have a significant peak when <span class="math inline">\(\frac{f_{x}(\omega_{[n/2]})}{[f_{x}(\omega_{[(n-1)/2]})]} \ge CV(\omega_{j})\)</span></p>
<p>Two significant levels for this test are considered: <span class="math inline">\(\alpha=0.05\)</span> (code “t”) and <span class="math inline">\(\alpha=0.01\)</span> (code “T”).</p>
<p>As opposed to the AR spectrum test, which is computed on the basis of the last <span class="math inline">\(120\)</span> data points, we will use here all available observations. Those critical values have been calculated given the recommended truncation lag <span class="math inline">\(r=79\)</span> for a sample size within the interval <span class="math inline">\(\in [80,119]\)</span> and <span class="math inline">\(r=112\)</span> for <span class="math inline">\(n \in [120,300]\)</span> . The <span class="math inline">\(F\)</span> approximation is less accurate for sample sizes larger than <span class="math inline">\(300\)</span>. For quarterly data, <span class="math inline">\(r=44\)</span>, but there are no recommendations regarding the required sample size.</p>
<p>Practical implementation in GUI is detailed <a href="T-GUI-Data-Viz-TS-Tools.html#t-GUI-tstools-id-p-tuckey">here</a></p>
</section>
<section id="in-ar-spectrum-definition" class="level3">
<h3 class="anchored" data-anchor-id="in-ar-spectrum-definition">In AR Spectrum definition</h3>
<p>The estimator of the spectral density at frequency <span class="math inline">\(\lambda \in [0,\pi]\)</span> will be given by the assumption that the series will follow an AR(p) process with large <span class="math inline">\(p\)</span>. The spectral density of such model, with an innovation variance <span class="math inline">\(var(x_{t})=\sigma^2_x\)</span>, is expressed as follows:</p>
<p><span class="math display">\[
10\times log_{10} f_x(\lambda)=10\times log_{10} \frac{\sigma^2_x}{2\pi |\phi(e^{i\lambda})|^2 }=10\times log_{10} \frac{\sigma^2_x}{2\pi |1-\sum_{k=1}^{p}\phi_k e^{i k \lambda})|^2 }
\]</span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(\phi_k\)</span> denotes the AR(k) coefficient ;</p></li>
<li><p><span class="math inline">\(e^{-ik\lambda}=cos⁡(-ik\lambda)+i sin⁡(-ik\lambda)\)</span>.</p></li>
</ul>
<p>Soukup and Findely (1999) suggest the use of p=30, which in practice much larger than the order that would result from the AIC criterion. The minimum number of observations needed to compute the spectrum is set to <em>n=80</em> for monthly data (or <em>n=60</em>) for quarterly series. In turn, the maximum number of observations considered for the estimation is <em>n=121</em>. This choice offers enough resolution, being able to identify a maximum of 30 peaks in a plot of 61 frequencies: by choosing <span class="math inline">\(\lambda_j=\pi j/60\)</span>,for <span class="math inline">\(j=0,1,…,60\)</span>, we are able to calculate our density estimates at exact seasonal frequencies (1, 2, 3, 4, 5 and 6 cycles per year). Note that <span class="math inline">\(x\)</span> cycles per year can be converted into cycles per month by simply dividing by twelve, <span class="math inline">\(x/12\)</span>, and to radians by applying the transformation <span class="math inline">\(2\pi(x/12)\)</span>.</p>
<p>The traditional trading day frequency corresponding to 0.348 cycles per month is used in place of the closest frequency <span class="math inline">\(\pi j/60\)</span>. Thus, we replace <span class="math inline">\(\pi 42/60\)</span> by <span class="math inline">\(\lambda_{42}=0.348\times 2 \pi=2.1865\)</span>. The frequencies neighbouring <span class="math inline">\(\lambda_{42}\)</span> are set to <span class="math inline">\(\lambda_{41}=2.1865-1/60\)</span> and <span class="math inline">\(\lambda_{43}=2.1865+1/60\)</span>. The periodogram below illustrates the proximity of this trading day frequency <span class="math inline">\(\lambda_{42}\)</span> (red shade) and the frequency corresponding to 4 cycles per year <span class="math inline">\(\lambda_{40}=2.0944\)</span>. This proximity is precisely what poses the identification problems: the AR spectrum boils down to a smoothed version of the periodogram and the contribution of the of the trading day frequency may be obscured by the leakage resulting from the potential seasonal peak at <span class="math inline">\(\lambda_{40}\)</span>, and vice-versa.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="All_images/UG_A_image19.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><strong>Periodogram with seasonal (grey) and calendar (red) frequencies highlighted</strong></figcaption>
</figure>
</div>
<p>JDemetra+ allows the user to modify the number of lags of this estimator and to change the number of observations used to determine the AR parameters. These two options can improve the resolution of this estimator.</p>
<p>The statistical significance of the peaks associated to a given frequency can be informally tested using a visual criterion, which has proved to perform well in simulation experiments. Visually significant peaks for a frequency <span class="math inline">\(\lambda_{j}\)</span> satisfy both conditions:</p>
<ul>
<li><p><span class="math inline">\(\frac{f_{x}(\lambda_{j})-\max \{f_{x}(\lambda_{j+1}),f_{x}(\lambda_{j-1})\}}{[\max_{k}f_{x}(\lambda_{k})-\min_{i}f_{x}(\lambda_{i})]}\ge CV(\lambda_{j})\)</span>, where <span class="math inline">\(CV(\lambda_{j})\)</span> can be set equal to <span class="math inline">\(6/52\)</span> for all <span class="math inline">\(j\)</span></p></li>
<li><p><span class="math inline">\(f_{x}(\lambda_{j})&gt; median_{j} \{ f_{x}(\lambda_{j})\}\)</span>, which guarantees <span class="math inline">\(f_{x}(\lambda_{j})\)</span> it is not a local peak.</p></li>
</ul>
<p>The first condition implies that if we divide the range <span class="math inline">\(\max_{k}f_{x}(\lambda_{k})-\min_{i}f_{x}(\lambda_{i})\)</span> in 52 parts (traditionally represented by stars) the height of each pick should be at least 6 stars.</p>
<p><strong>Seasonal and trading day frequencies by time series frequency</strong></p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Number of months per full period</strong></th>
<th><strong>Seasonal frequency</strong></th>
<th><strong>Trading day frequency (radians)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>12</td>
<td><span class="math inline">\(\frac{\pi}{6},\frac{\pi}{3},\ \frac{\pi}{2},\frac{2\pi}{3},\ \frac{5\pi}{6},\ \pi\)</span></td>
<td><span class="math inline">\(d\)</span>, 2.714</td>
</tr>
<tr class="even">
<td>6</td>
<td><span class="math inline">\(\frac{\pi}{3},\frac{2\pi}{3}\)</span>, <span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(d\)</span></td>
</tr>
<tr class="odd">
<td>4</td>
<td><span class="math inline">\(\frac{\pi}{2}\)</span>, <span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(d\)</span>, 1.292, 1.850, 2.128</td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(d\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(d\)</span></td>
</tr>
</tbody>
</table>
<p>Currently, only seasonal frequencies are tested, but the program allows you to manually plot the AR spectrum and focus your attention on both seasonal and trading day frequencies. Agustin Maravall has conducted a simulation experiment to calculate <span class="math inline">\(CV(\lambda_{42})\)</span> (trading day frequency) and proposes to set for all <span class="math inline">\(j\)</span> equal to the critical value associated to the trading frequency, but this is currently not part of the current automatic testing procedure of JDemetra+.</p>
<p>Practical implementation in GUI is detailed <a href="T-GUI-Data-Viz-TS-Tools.html#t-GUI-tstools-id-p-ar">here</a></p>
</section>
<section id="in-a-periodogram" class="level3">
<h3 class="anchored" data-anchor-id="in-a-periodogram">In a Periodogram</h3>
<p>The periodogram <span class="math inline">\(I(\omega_j)\)</span> of <span class="math inline">\(\mathbf{X} \in \mathbb{C}^n\)</span> is defined as the squared of the Fourier transform</p>
<p><span class="math display">\[
I(\omega_{j})=a_{j}^{2}=n^{-1}|\sum_{t=1}^{n}\mathbf{X_t} e^{-it\omega_j}|^{2},
\]</span></p>
<p>where the Fourier frequencies <span class="math inline">\(\omega_{j}\)</span> are given by multiples of the fundamental frequency <span class="math inline">\(\frac{2\pi}{n}\)</span>:</p>
<p><span class="math display">\[
\omega_{j}=\frac{2\pi j}{n},-\pi &lt; \omega_{j} \leq \pi
\]</span></p>
<p>An orthonormal basis in <span class="math inline">\(\mathbb{R}^n\)</span>:</p>
<p><span class="math display">\[
\{ e_0, ~~~~~~c_1, s_1, ~~~~~\ldots~~~~~\ , ~~~~c_{[(n-1)/2]}, s_{[(n-1)/2]}~~~~,~~~~~~ e_{n/2} \},
\]</span></p>
<p>where <span class="math inline">\(e_{n/2}\)</span> is excluded if <span class="math inline">\(n\)</span> is odd,</p>
<p>can be used to project the data and obtain the spectral decomposition</p>
<p>Thus, the periodogram is given by the projection coefficients and represents the contribution of the jth harmonic to the total sum of squares, as illustrated by Brockwell and Davis (1991):</p>
<table class="table">
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: center;">Degrees of freedom</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Frequency <span class="math inline">\(\omega_{0}\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>Frequency <span class="math inline">\(\omega_{1}\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td>Frequency <span class="math inline">\(\omega_{k}\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td>Frequency <span class="math inline">\(\omega_{n/2}=\pi\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td>(excluded if <span class="math inline">\(n\)</span> is odd)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td><span class="math inline">\(=========\)</span></td>
<td style="text-align: center;"><span class="math inline">\(======\)</span></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">n</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
~~~~
\]</span></p>
<p>In JDemetra+, the periodogram of <span class="math inline">\(\mathbf{X} \in \mathbb{R}^n\)</span> is computed for the standardized time series.</p>
<section id="defining-a-f-test" class="level4">
<h4 class="anchored" data-anchor-id="defining-a-f-test">Defining a F-test</h4>
<p>Brockwell and Davis (1991, section 10.2) exploit the fact that the periodogram can be expressed as the projection on the orthonormal basis defined above to derive a test. Thus, under the null hypothesis:</p>
<ul>
<li><span class="math inline">\(2I(\omega_{k})=\|P_{\bar{sp}_{\{ c_{k},s_{k}\}}} \mathbf{X} \|^{2} \sim \sigma^{2} \chi^{2}(2)\)</span>, for Fourier frequencies <span class="math inline">\(0 &lt; \omega_{k}=2\pi k/n &lt; \pi\)</span></li>
<li><span class="math inline">\(I(\pi)=\|P_{\bar{sp}_{\{ e_{n/2}\}}} \mathbf{X} \|^{2} \sim \sigma^{2} \chi^{2}(1)\)</span>, for <span class="math inline">\(\pi\)</span></li>
</ul>
<p>Because <span class="math inline">\(I(\omega_{k})\)</span> is independent from the projection error sum of squares, we can define our F-test statistic as follows:</p>
<ul>
<li><span class="math inline">\(\frac{ 2I(\omega_{k})}{\|\mathbf{X}-P_{\bar{sp}_{\{ e_0,c_{k},s_{k}\}}} \mathbf{X}\|^2} \frac{n-3}{2} \sim F(2,n-3)\)</span>, for Fourier frequencies <span class="math inline">\(0 &lt; \omega_{k}=2\pi k/n &lt; \pi\)</span></li>
<li><span class="math inline">\(\frac{ I(\pi)}{\|\mathbf{X}-P_{\bar{sp}_{\{ e_0,e_{n/2}\}}} \mathbf{X}\|^2} \frac{n-2}{1} \sim F(1,n-2)\)</span>, for <span class="math inline">\(\pi\)</span></li>
</ul>
<p>where:</p>
<p>-<span class="math inline">\(\|\mathbf{X}-P_{\bar{sp}_{\{ e_0,c_{k},s_{k}\}}} \mathbf{X}\|^2=\sum_{i=1}^{n}\mathbf{X^2_i}-I(0)-2I(\omega_{k}) \sim \sigma^{2} \chi^{2}(n-3)\)</span> for Fourier frequencies <span class="math inline">\(0 &lt; \omega_{k}=2\pi k/n &lt; \pi\)</span></p>
<p>-<span class="math inline">\(\|\mathbf{X}-P_{\bar{sp}_{\{ e_0,e_{n/2}\}}} \mathbf{X}\|^2=\sum_{i=1}^{n}\mathbf{X^2_i}-I(0)-I(\pi) \sim \sigma^{2} \chi^{2}(n-2)\)</span> for <span class="math inline">\(\pi\)</span></p>
<p>Thus, we reject the null if our F-test statistic computed at a given seasonal frequency (different from <span class="math inline">\(\pi\)</span>) is larger than <span class="math inline">\(F_{1-α}(2,n-3)\)</span>. If we consider <span class="math inline">\(\pi\)</span>, our test statistic follows a <span class="math inline">\(F_{1-α}(1,n-2)\)</span> distribution.</p>
<p>The implementation of JDemetra+ considers simultaneously the whole set of seasonal frequencies (1, 2, 3, 4, 5 and 6 cycles per year). Thus, the resulting test-statistic is:</p>
<p><span class="math display">\[
\frac{ 2I(\pi/6)+ 2I(\pi/3)+ 2I(2\pi/3)+ 2I(5\pi/6)+ \delta I(\pi)}{\|\mathbf{X}-P_{\bar{sp}_{\{ e_0,c_{1},s_{1},c_{2},s_{2},c_{3},s_{3},c_{4},s_{4},c_{5},s_{5}, \delta e_{n/2}\}}} \mathbf{X}\|^2} \frac{n-12}{11} \sim F(11-\delta,n-12+\delta)
\]</span></p>
<p>where <span class="math inline">\(\delta=1\)</span> if <span class="math inline">\(n\)</span> is even and 0 otherwise.</p>
<p>In small samples, the test performs better when the periodogram is evaluated as the exact seasonal frequencies. JDemetra+ modifies the sample size to ensure the seasonal frequencies belong to the set of Fourier frequencies. This strategy provides a very simple and effective way to eliminate the leakage problem.</p>
<p>Practical implementation in GUI is detailed <a href="T-GUI-Data-Viz-TS-Tools.html#t-GUI-tstools-id-p-per">here</a></p>
</section>
</section>
</section>
<section id="m-spectral-analysis-m-spectrum-graphs" class="level2">
<h2 class="anchored" data-anchor-id="m-spectral-analysis-m-spectrum-graphs">Spectral graphs</h2>
<p>The section below provides guidance on interpretation of spectral graphs, the display of which in the Graphical User Interface can be found <a href="T-GUI-Data-Viz-TS-Tools.html#t-GUI-tstools-spec-graphs">here</a></p>
<p>The interpretation of the spectral graph is rather straightforward. When the values of a spectral graph for low frequencies (i.e.&nbsp;one year and more) are large in relation to its other values it means that the long-term movements dominate in the series. When the values of a spectral graph for high frequencies (i.e.&nbsp;below one year) are large in relation to its other values it means that the series are rather trendless and contains a lot of noise. When the values of a spectral graph are distributed randomly around a constant without any visible peaks, then it is highly probable that the series is a random process. The presence of seasonality in a time series is manifested in a spectral graph by the peaks on the seasonal frequencies.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./P_Methods.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Methods</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./M-reg-arima-modelling.html" class="pagination-link">
        <span class="nav-page-text">Reg-ARIMA models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right"></div>
  </div>
</footer>



</body></html>